# Exercícios Módulo V - Pandas e Numpy - Curso Ciência de Dados do Zero:

In [1]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

Considere os arrays numpy X, Y abaixo:

In [2]:
from sklearn.datasets import load_iris

X = load_iris().data
Y = load_iris().target

In [3]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
Y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

__Exercício 1:__ Crie um dataframe df do pandas a partir de X, Y.

Primeiro, concatene os arrays numpy. Na sequência transforme o array final para um dataframe. Altere o nome das colunas para 'X1', 'X2', 'X3', 'X4' e 'target'.

In [5]:
#1.1Concatenação dos arrays X e Y:
XY_c_ = np.c_[X,Y]
#print(df)

#1.2Criando o DataFrame:
df = pd.DataFrame(XY_c_)

#Verificando o tamanho do DataFrame:
df.shape

#1.4Mostrando o DataFrame
df.head()



0    1    2    3    4
0  5.1  3.5  1.4  0.2  0.0
1  4.9  3.0  1.4  0.2  0.0
2  4.7  3.2  1.3  0.2  0.0
3  4.6  3.1  1.5  0.2  0.0
4  5.0  3.6  1.4  0.2  0.0

In [6]:
#1.5Renomeando as colunas
df.rename(columns = {0:"X1",1:"X2",2:"X3",3:"X4",4:"target"}, inplace=True)

#1.6Mostrando o DataFrame com as colunas renomeadas:
df.head(150)

#Retorna todos os nomes das colunas:
df.columns

Index(['X1', 'X2', 'X3', 'X4', 'target'], dtype='object')

__Exercício 2:__ Usando o df criano no exercício 1, calcule qual a média da variável 'X2', para cada valor de target. Dica: Use a função groupby no dataframe df para resolver.

In [7]:
df[['X2','target']].groupby(['target']).mean()

X2
target       
0.0     3.428
1.0     2.770
2.0     2.974

__Exercício 3:__ Construa um dicionário mapeando os valores:
        
        0 - 'A'
        
        1 - 'B'
        
        2 - 'C'
        
Usando a função map, crie uma coluna nova no dataframe df chamada 'target_2' com o mapeamento feito. Dica: Use a função map como visto em aula.

In [8]:
df['target_2'] = df['target'].map({0.0:'A',1.0:'B',2.0:'C'})

In [9]:
df.head(150)

X1   X2   X3   X4  target target_2
0    5.1  3.5  1.4  0.2     0.0        A
1    4.9  3.0  1.4  0.2     0.0        A
2    4.7  3.2  1.3  0.2     0.0        A
3    4.6  3.1  1.5  0.2     0.0        A
4    5.0  3.6  1.4  0.2     0.0        A
..   ...  ...  ...  ...     ...      ...
145  6.7  3.0  5.2  2.3     2.0        C
146  6.3  2.5  5.0  1.9     2.0        C
147  6.5  3.0  5.2  2.0     2.0        C
148  6.2  3.4  5.4  2.3     2.0        C
149  5.9  3.0  5.1  1.8     2.0        C

[150 rows x 6 columns]

__Exercício 4:__ 


4.1: Filtre o dataframe df onde X1 é maior do que 6 ou target é diferente de 2 e chame-o de df1. Dica: usar os filtros e os operadores vistos em aula;

In [10]:
#Descartando a coluna target_2 do DataFrame para poder realizar as operações matemáticas com os arrays
df = df.drop(["target_2"], axis=1)

In [11]:
df1 = df[(df.X1>6) | (df.target!=2)]
df1.head(150)


X1   X2   X3   X4  target
0    5.1  3.5  1.4  0.2     0.0
1    4.9  3.0  1.4  0.2     0.0
2    4.7  3.2  1.3  0.2     0.0
3    4.6  3.1  1.5  0.2     0.0
4    5.0  3.6  1.4  0.2     0.0
..   ...  ...  ...  ...     ...
144  6.7  3.3  5.7  2.5     2.0
145  6.7  3.0  5.2  2.3     2.0
146  6.3  2.5  5.0  1.9     2.0
147  6.5  3.0  5.2  2.0     2.0
148  6.2  3.4  5.4  2.3     2.0

[141 rows x 5 columns]

4.2: Filtre os primeiros 15 índices do dataframe df e chame-o de df2;

In [12]:
df2 = df[:15]
df2.head(15)

X1   X2   X3   X4  target
0   5.1  3.5  1.4  0.2     0.0
1   4.9  3.0  1.4  0.2     0.0
2   4.7  3.2  1.3  0.2     0.0
3   4.6  3.1  1.5  0.2     0.0
4   5.0  3.6  1.4  0.2     0.0
5   5.4  3.9  1.7  0.4     0.0
6   4.6  3.4  1.4  0.3     0.0
7   5.0  3.4  1.5  0.2     0.0
8   4.4  2.9  1.4  0.2     0.0
9   4.9  3.1  1.5  0.1     0.0
10  5.4  3.7  1.5  0.2     0.0
11  4.8  3.4  1.6  0.2     0.0
12  4.8  3.0  1.4  0.1     0.0
13  4.3  3.0  1.1  0.1     0.0
14  5.8  4.0  1.2  0.2     0.0


4.3: Transformando os dataframes df1 e df2 para arrays. Multiplique df1 pelo transposto de df2 (use a função que calcula transposta de matriz) e printe o resultado final. Lembre-se de dropar a coluna target_2 de cada um dos dataframes antes de fazer a mutliplicação.

In [13]:
#Transformando df1 em um array:
df1_array = df1.values
df1_array

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [14]:
#Transformando df1 em um array:
df2_array = df2.values
df2_array

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ]])

In [15]:
#Transposta de df2
df2_array.T

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. ],
       [1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
        1.1, 1.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
        0.1, 0.2],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. ]])

In [16]:
#verificando o tamnho da matriz df1_array
df1_array.shape

(141, 5)

In [17]:
#verificando o tamnho da matriz df2_array.T
df2_array.T.shape

(5, 15)

In [18]:
#Multiplicação das matrizes df1_array e df2_array
np.dot(df1_array, df2_array.T)

array([[40.26, 37.49, 37.03, ..., 36.96, 33.99, 45.3 ],
       [37.49, 35.01, 34.49, ..., 34.5 , 31.63, 42.14],
       [37.03, 34.49, 34.06, ..., 34.  , 31.26, 41.66],
       ...,
       [48.26, 45.75, 44.49, ..., 44.93, 40.28, 52.92],
       [51.33, 48.53, 47.31, ..., 47.68, 42.87, 56.34],
       [51.54, 48.6 , 47.5 , ..., 47.75, 43.03, 56.5 ]])

__Exercício 5:__ 
    
5.1: Crie uma função que receba um  número inteiro positivo N e retorne um array 0, 1, ..., N. Dica: Use as funções que vimos para criação de arrays;
    




In [19]:
def criaArray():
    N = int(input("Informe um valor inteiro: "))
    array_N = np.arange(N+1)
    return array_N

criaArray()

Informe um valor inteiro: 10


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

5.2: Crie uma função que receba um array [0,1, .., N] e retorne o mesmo array, só que com os números em posições aleatórias. Dica: use a função que vimos em aula que faz escolhas aleatórias SEM reposição;




In [21]:
N = int(input("Informe um valor inteiro: "))
array_N = np.arange(N+1)
def criaArray_aleatorio():
    array_copia = array_N.copy()
    np.random.shuffle(array_copia)
    print(array_copia)


criaArray_aleatorio()
print(array_N)

Informe um valor inteiro: 10
[ 3  5  1  9  7  6  4  0  2  8 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [43]:
# OBS: Professora, aqui eu fiz o exercício de duas formas, usando o choice e o shuffle, pois me bati um monte para conseguir. 
# Gostaria que me desse o feedback em relação as duas formas feitas. Se possível.
def criaArray_aleatorio():
    array_aleatorio = np.random.choice(array_N, array_N.shape, replace=False)
    return array_aleatorio

criaArray_aleatorio()


array([10,  5,  8,  0,  3,  4,  6,  1,  2,  9,  7])

5.3: Crie uma função que receba um número inteiro positivo N. Essa função deve retornar um array de tamanho N, cujos valores são números inteiros entre 0 e N-1 e pode haver repetição desses números.

In [38]:
def criaArray_aleatorio():
    N = int(input("Informe um valor inteiro: "))
    array_N = np.arange(N-1)
    array_aleatorio = np.random.choice(array_N, array_N.shape)
    return array_aleatorio

criaArray_aleatorio()

Informe um valor inteiro: 10


array([4, 2, 5, 3, 4, 6, 5, 6, 0])

__Exercício 6:__ Construa uma função divide_dados:
        
- recebe um array X de dimensões quaisquer (n,k) e um parâmetro p entre 0 e 1.
- divide o array X em duas partes disjuntas de forma aleatória. Ou seja, crie dois novos arrays, X1 e X2,
onde a dimensão de linhas de X1 somada com a dimensão de linhas de X2 deve ser igual a dimensão de linhas de X.
- interpretando p como percentual, o tamanho de X1 deve ser p*100% do número de linhas de X; enquanto X2 deve ser o resto.
- retorne esses dois arrays.

       

In [39]:
X = np.arange(int(input("Digite um valor inteiro:")))
p = np.random.random(1)
print(p)
def split_array(X,p): 
    copia_x = X.copy()
    print(copia_x)
    np.random.shuffle(copia_x) 
    print(copia_x)
    linhas_x1 = int(len(copia_x)*p) 
    x1 = copia_x[:linhas_x1] 
    x2 = copia_x[linhas_x1:]
    return x1,x2

split_array(X,p)

Digite um valor inteiro:16
[0.76799409]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 4  1 13  2  0 15 11  8  7 10 14  5  3 12  9  6]


(array([ 4,  1, 13,  2,  0, 15, 11,  8,  7, 10, 14,  5]),
 array([ 3, 12,  9,  6]))